In [5]:
import pandas as pd

In [9]:
data = pd.read_csv("Desktop/dataset_readmissions_datathon_HUS_2022.csv", encoding="unicode_escape")

In [37]:
def get_patient(dataset, patientID):
    
    out_patient  = dataset[dataset['patientID']==patientID]

    return out_patient

def save_excel(dataset,patientID):

        out_patient  = dataset[dataset['patientID']==patientID]

        out_patient.to_excel("patient_excel.xlsx")

In [19]:
pd.unique(data['readmission'])

array([ 0.,  1., nan])

In [20]:
sum(data['mors'])

8459

In [28]:
data[data['mors']==1]

,Unnamed: 0,bed_day_dep,DRG,gender,timestamp_in,timestamp_out,degree_of_urgency,patientID,hosp_unique_ID,mainDiagICD10Chapter,...,diagnosis_code_4,diagnosis_code_5,diagnosis_code_6,diagnosis_code_7,diagnosis_code_8,diagnosis_code_9,age_group,bed_day_hosp,readmission,mors
19,19,NaN,NaN,NaN,1349,1349,NaN,12,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
29,29,NaN,NaN,NaN,878,878,NaN,14,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
74,74,NaN,NaN,NaN,559,559,NaN,28,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
97,97,NaN,NaN,NaN,975,975,NaN,35,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
116,116,NaN,NaN,NaN,497,497,NaN,43,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236381,236381,NaN,NaN,NaN,626,626,NaN,117179,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
237103,237103,NaN,NaN,NaN,228,228,NaN,117632,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
239552,239552,NaN,NaN,NaN,583,583,NaN,119206,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
241901,241901,NaN,NaN,NaN,239,239,NaN,120733,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
241915,241915,NaN,NaN,NaN,1,1,NaN,120741,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [31]:
#Count readmissions
data['readmission'].value_counts()

0.0    215218
1.0     18889
Name: readmission, dtype: int64

In [35]:
#Number of ptients
nr_patients = len(pd.unique(data['patientID']))

In [40]:
#Remove first row, due to data issues
data = data.drop([0])

In [75]:
count

13176

In [63]:
flat_list = [item for sublist in diff_code for item in sublist]

In [65]:
diff_code_data = ra_patients_data.iloc[flat_list]

In [88]:
pair_dict = {}

In [77]:
ad_data = diff_code_data[diff_code_data['readmission']==0]

In [78]:
ad_diag = pd.unique(ad_data['diagnosis_code_1'])

In [109]:
diff_code_data[diff_code_data['diagnosis_code_1']=='M6504']

,Unnamed: 0,bed_day_dep,DRG,gender,timestamp_in,timestamp_out,degree_of_urgency,patientID,hosp_unique_ID,mainDiagICD10Chapter,...,diagnosis_code_4,diagnosis_code_5,diagnosis_code_6,diagnosis_code_7,diagnosis_code_8,diagnosis_code_9,age_group,bed_day_hosp,readmission,mors
1984,1984,1.0,0.386,1.0,1157,1157,1.0,791,34383.0,Kapittel XIII (M00-M99) Sykdommer i muskel-skj...,...,F1122,NaN,NaN,NaN,NaN,NaN,40-49,18.0,1.0,0
1984,1984,1.0,0.386,1.0,1157,1157,1.0,791,34383.0,Kapittel XIII (M00-M99) Sykdommer i muskel-skj...,...,F1122,NaN,NaN,NaN,NaN,NaN,40-49,18.0,1.0,0
1986,1986,16.0,2.043,1.0,1157,1173,1.0,791,34383.0,Kapittel XIII (M00-M99) Sykdommer i muskel-skj...,...,D509,F1122,F132,S221,S619,NaN,40-49,18.0,1.0,0
8169,8169,3.0,0.942,1.0,573,575,1.0,3440,573355.0,Kapittel XIII (M00-M99) Sykdommer i muskel-skj...,...,NaN,NaN,NaN,NaN,NaN,NaN,50-59,20.0,1.0,0
8171,8171,1.0,0.367,1.0,639,639,1.0,3440,573355.0,Kapittel XIII (M00-M99) Sykdommer i muskel-skj...,...,S619,NaN,NaN,NaN,NaN,NaN,50-59,20.0,1.0,0
23995,23995,9.0,1.781,1.0,23,32,1.0,10783,533338.0,Kapittel XIII (M00-M99) Sykdommer i muskel-skj...,...,R001,NaN,NaN,NaN,NaN,NaN,30-39,9.0,1.0,0
40754,40754,7.0,1.781,1.0,69,75,1.0,18326,311043.0,Kapittel XIII (M00-M99) Sykdommer i muskel-skj...,...,NaN,NaN,NaN,NaN,NaN,NaN,50-59,7.0,1.0,0

In [ ]:
#Deaths not happening at the hospital within 30 days of admission

In [113]:
death_pat_data = data[data['mors']==1]

death_pat = pd.unique(death_pat_data['patientID'])

In [232]:
death_30=[]
for k in death_pat:
    tmp = data[data['patientID']==k]
    
    death_time = tmp['timestamp_in'].iloc[-1]-tmp['timestamp_out'].iloc[-2]
    
    if death_time<30 and death_time>1:
        death_30.append(k)

In [233]:
len(death_30)
#119 people die less than 30 days from last admission

119

In [234]:
death_30[-1]

106004

In [113]:
#Create new variable for admission leading to readmission
data['lead_to_readmission'] = data['readmission'].shift(periods=-1, fill_value=0)

In [238]:
#Set admission before the 119 deaths as leading to readmission
for k in death_30:
    tmp_ind = data.index[data['patientID']==k]
    data.loc[tmp_ind[-2],'lead_to_readmission']=1

In [243]:
#Remove all deaths
data_drop_death = data.drop(data[data['mors']==1].index)

In [250]:
data_drop_death.shape
#234106 data points left

(234106, 25)

In [245]:
#Remove diagnosis codes >1 
data_drop_death_drop_diag = data_drop_death.drop(['diagnosis_code_2','diagnosis_code_3', 'diagnosis_code_4', 'diagnosis_code_5', 'diagnosis_code_6', 'diagnosis_code_7', 'diagnosis_code_8', 'diagnosis_code_9'], axis=1)

In [246]:
data_drop_death_drop_diag.shape

(234106, 17)

In [247]:
#Remove data points with missing values
almost final data = data_drop_death_drop_diag.dropna()

,Unnamed: 0,bed_day_dep,DRG,gender,timestamp_in,timestamp_out,degree_of_urgency,patientID,hosp_unique_ID,mainDiagICD10Chapter,mainDiagBlock,diagnosis_code_1,age_group,bed_day_hosp,readmission,mors,lead_to_readmission
1,1,1.0,0.197,1.0,1,1,1.0,1,327304.0,Kapittel VI (G00-G99) Sykdommer i nervesystemet,"(G50-G59) Sykdommer i nerver, nerverøtter og n...",G510,50-59,1.0,0.0,0,0.0
2,2,1.0,0.317,2.0,1,1,4.0,2,71426.0,Kapittel XIV (N00-N99) Sykdommer i urin- og kj...,(N30-N39) Andre forstyrrelser i urinsystemet,N394,60-69,1.0,0.0,0,0.0
3,3,2.0,0.611,2.0,1,2,1.0,3,98861.0,Kapittel VI (G00-G99) Sykdommer i nervesystemet,(G40-G47) Episodiske tilstander og anfallsvise...,G431,50-59,2.0,0.0,0,0.0
4,4,6.0,4.283,2.0,1,6,4.0,4,318366.0,"Kapittel XIX (S00-T98) Skader, forgiftninger o...",(T80-T88) Komplikasjoner til kirurgisk og medi...,T844,50-59,6.0,0.0,0,0.0
5,5,2.0,1.050,1.0,1,2,4.0,5,499752.0,Kapittel VI (G00-G99) Sykdommer i nervesystemet,(G20-G26) Ekstrapyramidale tilstander og beveg...,G20,50-59,2.0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242560,242560,1.0,0.526,2.0,1,1,1.0,121191,184045.0,Kapittel XVI (P00-P96) Visse tilstander som op...,(P90-P96) Andre forstyrrelser som oppstår i pe...,P925,0-9,1.0,0.0,0,0.0
242561,242561,1.0,0.526,2.0,1,1,4.0,121192,264301.0,Kapittel XVI (P00-P96) Visse tilstander som op...,(P90-P96) Andre forstyrrelser som oppstår i pe...,P925,0-9,1.0,0.0,0,0.0
242563,242563,2.0,0.526,2.0,1,2,1.0,121194,219110.0,Kapittel XXI (Z00-Z99) Faktorer som har betydn...,(Z00-Z13) Kontakt med helsetjenesten for under...,Z0011,0-9,2.0,0.0,0,0.0
242564,242564,1.0,0.034,1.0,1,1,1.0,121195,156798.0,Kapittel XVI (P00-P96) Visse tilstander som op...,(P20-P29) Respiratoriske og kardiovaskulære fo...,P221,0-9,3.0,0.0,0,0.0
242565,242565,3.0,0.526,1.0,1,3,1.0,121195,156798.0,Kapittel XXI (Z00-Z99) Faktorer som har betydn...,(Z00-Z13) Kontakt med helsetjenesten for under...,Z0011,0-9,3.0,0.0,0,0.0

In [248]:
data_drop_death_drop_diag.shape

(234106, 17)

In [253]:
#Remove readmissions
final_data = almost_final_data.drop(almost_final_data[almost_final_data['readmission']==1].index)

In [254]:
final_data.shape
#207261 data points for training and testing

(207261, 17)

In [255]:
#Save data to use for training
final_data.to_csv('final_data.csv')

In [257]:
final_data[final_data['lead_to_readmission']==0].describe()

In [258]:
final_data.groupby(by='lead_to_readmission').count()

,Unnamed: 0,bed_day_dep,DRG,gender,timestamp_in,timestamp_out,degree_of_urgency,patientID,hosp_unique_ID,mainDiagICD10Chapter,mainDiagBlock,diagnosis_code_1,age_group,bed_day_hosp,readmission,mors
lead_to_readmission,,,,,,,,,,,,,,,,
0.0,190614,190614,190614,190614,190614,190614,190614,190614,190614,190614,190614,190614,190614,190614,190614,190614
1.0,16647,16647,16647,16647,16647,16647,16647,16647,16647,16647,16647,16647,16647,16647,16647,16647

In [213]:
#Check age-distribution
#DIDN'T FINISH THIS AND DIDN'T USE IT
age_dist = {}
for i in death_30:
    tmp = data[data['patientID']==i]
    age = tmp['age_group'].iloc[-2]  
    
    if age=='nan':
        print(i)
    
    if age in age_dist:
        age_dist[age]+=1
    else:
        age_dist[age]=1    
        
grouped = data.groupby(['age_group'])

In [ ]:
#Previously had readmissions
#DIDN'T FINISH THIS AND DIDN'T USE IT
data['prev_readmission']=0
for i in pd.unique(data['patientID']):
    tmp = get_patient(data,i)

In [ ]:
#Get admission/readmission pairs which are different
#DIDN*T FINISH THIS AND DIDN*T USE IT
readmission_data = data[data['readmission']==1]
ra_patients = pd.unique(readmission_data['patientID'])
ra_patients_data = data[data['patientID'].isin(ra_patients)]
readmission_list = ra_patients_data['readmission']

indices = []
for i, val in enumerate(readmission_list):
    if val == 1:
        indices.append([i-1,i])
diff_code = []
count = 0
count2=0

for x in indices:
    pair = ra_patients_data.iloc[x]
    
    if len(pd.unique(pair['diagnosis_code_1']))>1:
        diff_code.append(x)
        count+=1
    if len(pd.unique(pair['diagnosis_code_1']))==1:
        count2 +=1